spring.application.name=${spring.application.name.jobs}

server.port=8082

# Postgres settings
spring.datasource.url=jdbc:postgresql://localhost:5232/job
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=false

# Logging
logging.level.org.hibernate.SQL=debug

# SQL script settings
spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:sql/schema.sql
#spring.sql.init.data-locations=classpath:sql/data.sql

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Zipkin
management.tracing.sampling.probability=1.0

#Config server
spring.config.import=optional:configserver:http://localhost:8080
spring.profiles.active=dev

#Resilience4J
resilience4j.circuitbreaker.instances.companyBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.companyBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.companyBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.companyBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.companyBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.companyBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.companyBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.companyBreaker.sliding-window-type=count_based

resilience4j.circuitbreaker.instances.companyBreaker.max-attempts=5
resilience4j.circuitbreaker.instances.companyBreaker.wait-duration=2s
resilience4j.retry.metrics.legacy.enabled=true
resilience4j.retry.metrics.enabled=true

resilience4j.circuitbreaker.instances.companyBreaker.timeout-duration=0
resilience4j.circuitbreaker.instances.companyBreaker.limit-refreshg-period=4
resilience4j.circuitbreaker.instances.companyBreaker.limit-for-period=2

#Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
#management.endpoint.shutdown.enabled=true
#server.shutdown=graceful

#Others
management.info.env.enabled=true
info.app.name=JobApplication
info.app.description=Job Application by Falynsky
info.app.version=1.0.0
